




# Подключение и получение ответа от Мозга

curl -X POST http://usa:3002/api/send-request \
-H "Content-Type: application/json" \
-d '{"model": {model}, "prompt": {prompt}, "inputText": "{inputText}", "saveResponse": true}'

model - модель мозга (CHEAP, REACH, FAST) - пока на стадии разработки везде используем REACH
prompt - prompt для мозга
inputText - входной текст
saveResponse - сохранять ответ от мозга

## Пример:
curl -X POST http://usa:3002/api/send-request \
-H "Content-Type: application/json" \
-d '{"model": "REACH", "prompt": "Ты полезный помощник", "inputText": "Привет!", "saveResponse": true}'